# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
---
name: Python package
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install System dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq cmake ffmpeg screen
        sudo apt-get install -qq liblzma-dev libxml2-dev libxslt-dev libyaml-dev libz-dev
        sudo apt-get install -qq libcairo2 libcairo2-dev libexiv2-dev libgexiv2-dev libgirepository-2.0-dev
    - name: Install Python dependencies
      run: |
        pip install -U pip setuptools wheel
        pip install -U -e .[all,test]
        pip freeze
    - name: Debug env
      run: |
        env | sort | grep -i -E 'COLOR|TERM|CI'
    - name: Test with pytest
      run: |
        python -m pytest -vvvv
    - name: Coveralls
      uses: coverallsapp/github-action@v2

  build-windows:
    runs-on: windows-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - name: Install System dependencies
      run: choco install ffmpeg --no-progress -y
    - name: Install Python dependencies
      run: |
        pip install -U pip setuptools wheel
        pip install -U -e .[atlassian,aws,django,django_filter,django_formtools,flask,jinja2,mongodb,network,pandas,rest_framework,selenium,voluptuous,test]
        pip freeze
    - name: Debug env
      run: |
        env | sort | grep -i -E 'COLOR|TERM|CI'
      shell: bash
    - name: Test with pytest
      run: |
        python -m pytest -vvvv --ignore=pytoolbox/ai --ignore=pytoolbox/multimedia/image --ignore=pytoolbox/network/smpte2022
...
